# C:\Users\User\Desktop\project_two\front-end\docker-compose.yml

# The 'version' attribute is now obsolete in Docker Compose v2.
# Removing it makes the file cleaner and avoids warnings.

services:
  frontend:
    build:
      context: . # Build context is the current directory (front-end)
      dockerfile: Dockerfile # Use the Dockerfile in the current directory
    container_name: nextjs-frontend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000 # Placeholder for local testing. Will change later.
    # volumes: # Keep this commented out unless you specifically need live reloading for local dev
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped # Restart policy
