    # C:\Users\User\Desktop\project_two\front-end\.github\workflows\nextjs-ci.yml
    name: Next.js CI/CD to Docker Hub

    on:
      push:
        branches:
          - main # Trigger on push to the main branch
      pull_request:
        branches:
          - main # Trigger on pull requests to the main branch

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_IMAGE_NAME: kidest/front-end-frontend # Your specified image name

    jobs:
      build-and-push:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ env.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              # --- FIX IS HERE ---
              # Each tag should be on its own line without comments after it.
              tags: |
                ${{ env.DOCKER_IMAGE_NAME }}:latest
                ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
              # --- END FIX ---
    