# C:\Users\User\Desktop\project_two\front-end\.github\workflows\nextjs-ci.yml
name: Next.js CI/CD to Docker Hub

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

env:
  # Environment variables for Docker Hub login and image naming
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # This will be set by GitHub Secret
  # Docker image name on Docker Hub
  DOCKER_IMAGE_NAME: kidest/front-end-frontend # Updated to your specified image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run on a fresh Ubuntu virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for advanced builds

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Use a fine-grained access token for security

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of the repo (your front-end directory)
          file: ./Dockerfile # Path to your Dockerfile relative to the context
          push: true # Push the image to Docker Hub
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest # Tag as latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Tag with commit SHA for versioning
